src/Tracker/TicketBundle/Entity/Ticket.php
<?php

namespace Tracker\TicketBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Ticket
 */
class Ticket
{
    const TYPE_TECHNICAL  = 1;
    const TYPE_COMMERCIAL = 2;
    
    /**
     * @var integer
     */
    private $id;

    /**
     * @var integer
     */
    private $type;

    /**
     * @var string
     */
    private $name;
    
    /**
     * @var string
     */
    private $description;
    
    /**
     * @var \DateTime
     */
    private $created;
    
    /**
     * @var \DateTime
     */
    private $closed;

    /**
     * @var \Tracker\UserBundle\Entity\User
     */
    private $user;
    
    /**
     * @var \Doctrine\Common\Collections\Collection
     */
    private $messages;

    /**
     * Constructor
     */
    public function __construct()
    {
        $this->messages = new \Doctrine\Common\Collections\ArrayCollection();
    }


    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set type
     *
     * @param integer $type
     * @return Ticket
     */
    public function setType($type)
    {
        $this->type = $type;

        return $this;
    }

    /**
     * Get type
     *
     * @return integer 
     */
    public function getType()
    {
        return $this->type;
    }
    
    /**
     * Get type description
     *
     * @return string 
     */
    public function getTypeDescription()
    {
        $message = '';
        switch($this->type) {
            case self::TYPE_TECHNICAL:
               $message = 'Support Technique';
               break;
            case self::TYPE_COMMERCIAL:
                $message = 'Support commercial';
                break;
        }
        
        return $message;
    }

    /**
     * Set name
     *
     * @param string $name
     * @return Ticket
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Get name
     *
     * @return string 
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Set created
     *
     * @param \DateTime $created
     * @return Ticket
     */
    public function setCreated($created)
    {
        $this->created = $created;

        return $this;
    }

    /**
     * Get created
     *
     * @return \DateTime 
     */
    public function getCreated()
    {
        return $this->created;
    }

    /**
     * Set user
     *
     * @param \Tracker\UserBundle\Entity\User $user
     * @return Ticket
     */
    public function setUser(\Tracker\UserBundle\Entity\User $user = null)
    {
        $this->user = $user;

        return $this;
    }

    /**
     * Get user
     *
     * @return \Tracker\UserBundle\Entity\User 
     */
    public function getUser()
    {
        return $this->user;
    }
    
    /**
     * @ORM\PrePersist
     */
    public function prePersist()
    {
        $this->created = new \DateTime();
    }

    /**
     * Set description
     *
     * @param string $description
     * @return Ticket
     */
    public function setDescription($description)
    {
        $this->description = $description;

        return $this;
    }

    /**
     * Get description
     *
     * @return string 
     */
    public function getDescription()
    {
        return $this->description;
    }
    


    /**
     * Set closed
     *
     * @param \DateTime $closed
     * @return Ticket
     */
    public function setClosed($closed)
    {
        $this->closed = $closed;

        return $this;
    }

    /**
     * Get closed
     *
     * @return \DateTime 
     */
    public function getClosed()
    {
        return $this->closed;
    }

    /**
     * Add messages
     *
     * @param \Tracker\TicketBundle\Entity\Message $messages
     * @return Ticket
     */
    public function addMessage(\Tracker\TicketBundle\Entity\Message $messages)
    {
        $this->messages[] = $messages;

        return $this;
    }

    /**
     * Remove messages
     *
     * @param \Tracker\TicketBundle\Entity\Message $messages
     */
    public function removeMessage(\Tracker\TicketBundle\Entity\Message $messages)
    {
        $this->messages->removeElement($messages);
    }

    /**
     * Get messages
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getMessages()
    {
        return $this->messages;
    }
}

src/Tracker/TicketBundle/Form/TicketType.php
<?php

namespace Tracker\TicketBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

use Tracker\TicketBundle\Entity\Ticket;

class TicketType extends AbstractType
{
        /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
        	->add('name', 'text', array(
        	    'attr' => array('placeholder' => 'Titre du ticket'),
        	    'error_bubbling' => true
        	))
            ->add('type', 'choice', array(
            	'choices' => array(
            		Ticket::TYPE_TECHNICAL  => 'Technique',
            		Ticket::TYPE_COMMERCIAL => 'Commercial'
            	),
            	'empty_value' => 'Type de support',
            	'error_bubbling' => true
            ))
            ->add('description', 'textarea', array(
                'attr' => array('placeholder' => 'Contenu de votre message'),
                'error_bubbling' => true
            ))
        ;
    }
    
    /**
     * @param OptionsResolverInterface $resolver
     */
    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'Tracker\TicketBundle\Entity\Ticket'
        ));
    }

    /**
     * @return string
     */
    public function getName()
    {
        return 'tracker_ticketbundle_ticket';
    }
}

src/Tracker/TicketBundle/Controller/TicketController.php
<?php

namespace Tracker\TicketBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\Security\Core\Exception\AccessDeniedException;

use Tracker\TicketBundle\Entity\Ticket;
use Tracker\TicketBundle\Form\TicketType;
use Tracker\TicketBundle\Entity\Message;
use Tracker\TicketBundle\Form\MessageType;

class TicketController extends Controller
{
    public function indexAction()
    {
        $tickets = $this
            ->getDoctrine()
            ->getManager()
            ->getRepository('TrackerTicketBundle:Ticket')
            ->findBy(array('user' => $this->getUser()), array('created' => 'DESC'));
        
        return $this->render('TrackerTicketBundle:Ticket:index.html.twig', array(
            'tickets' => $tickets
        ));
    }
    
    public function viewAction(Ticket $ticket)
    {
        if( $ticket->getUser()->getId() != $this->getUser()->getId() )
            throw new AccessDeniedException();
        
        $message = new Message();
        $form = $this->createForm(new MessageType(), $message);
        $request = $this->get('request');
        
        $form->handleRequest($request);
        if ($form->isSubmitted()) 
        {
            if( $form->isValid() ) 
            {
                $em = $this->getDoctrine()->getManager();
                
                if( $message->getClose() )
                {
                    $ticket->setClosed(new \DateTime());
                    $em->persist($ticket);
                    $em->flush();
                }
                
                $message->setUser($this->getUser());
                $message->setTicket($ticket);
                $em->persist($message);
                $em->flush();
                return $this->redirect($this->generateUrl('tracker_ticket_ticket_view', array('id' => $ticket->getId())));
            }
        }
        
        $ticket = $this
            ->getDoctrine()
            ->getManager()
            ->getRepository('TrackerTicketBundle:Ticket')
            ->find($ticket->getId());
        
        return $this->render('TrackerTicketBundle:Ticket:view.html.twig', array(
            'ticket' => $ticket,
            'form' => $form->createView()
        ));
    }
    
    public function addAction()
    {
        $ticket = new Ticket();
        $form = $this->createForm(new TicketType(), $ticket);
        $request = $this->get('request');
        
        $form->handleRequest($request);
        if ($form->isSubmitted()) 
        {
            if( $form->isValid() ) 
            {
                $ticket->setUser($this->getUser());
                $em = $this->getDoctrine()->getManager();
                $em->persist($ticket);
                $em->flush();
                return $this->redirect($this->generateUrl('tracker_ticket_ticket_index'));
            }
        }
        
        return $this->render('TrackerTicketBundle:Ticket:add.html.twig', array(
            'form' => $form->createView()
        ));
    }
}

src/Tracker/TicketBundle/Resources/views/Ticket/add.html.twig
{% extends "TrackerTicketBundle::layout.html.twig" %}

{% block breadcrumb %}
	<li><a href="{{ path('tracker_page_dashboard') }}">{{ 'Accueil'|trans }}</a></li>
	<li><a href="{{ path('tracker_ticket_ticket_index') }}">{{ 'Tickets'|trans }}</a></li>
	<li>{{ 'Ouverture'|trans }}</li>
{% endblock %}

{% block ticket_body %}
<div id="content">
	<div class="row">
		<div class="col-xs-12 col-sm-7 col-md-7 col-lg-4">
			<h1 class="page-title txt-color-blueDark"><i class="fa-fw fa fa-table"></i> {{ 'Tickets'|trans }} </span></h1>
		</div>
	</div>
	
	<section id="widget-grid" class="">
		<div class="row">
			<article class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
				<div class="jarviswidget">
					<header>
						<span class="widget-icon"><i class="fa fa-edit"></i></span>
						<h2>Ouverture d'un ticket</h2>
					</header>
					<div>
    					<div class="widget-body no-padding">
                            {% if not form.vars.valid %}
                                <div class="alert alert-danger">
                                    <button class="close"> x </button>
                                    <i class="fa-fw fa fa-times"></i>
                                    <strong>Une erreur est survenue!</strong>
                                    {{ form_errors(form) }}
                                </div>
                            {% endif %}
                            <form class="smart-form" method="post">
                                <fieldset>
                                    <div class="row">
                                        <section class="col col-6">
                                            <label class="input">
                                                <i class="icon-prepend fa fa-tag"></i>
                                                {{ form_widget(form.name) }}
                                            </label>
                                        </section>
                                        <section class="col col-6">
                                            <label class="select"> 
                                                {{ form_widget(form.type) }}
                                                <i></i>
                                            </label>
                                        </section>
                                    </div>
                                    <section>
                                        <label class="textarea">
                                            <i class="icon-append fa fa-comment"></i>
                                            {{ form_widget(form.description) }}
                                        </label>
                                    </section>
                                </fieldset>
                                
                                {{ form_rest(form) }}
                                
                                <footer>
                                    <button class="btn btn-primary" type="submit">Valider</button>
                                </footer>
                            </form>
                        </div>
                    </div>
				</div>
			</article>
		</div>
	</section>
</div>
{% endblock %}

src/Tracker/TicketBundle/Resources/views/Ticket/index.html.twig
{% extends "TrackerTicketBundle::layout.html.twig" %}

{% block breadcrumb %}
	<li><a href="{{ path('tracker_page_dashboard') }}">{{ 'Accueil'|trans }}</a></li>
	<li>{{ 'Tickets'|trans }}</li>
{% endblock %}

{% block ticket_body %}
<div id="content">
	<div class="row">
		<div class="col-xs-12 col-sm-7 col-md-7 col-lg-4">
			<h1 class="page-title txt-color-blueDark"><i class="fa-fw fa fa-table"></i> {{ 'Tickets'|trans }} </span></h1>
		</div>
	</div>
	
	<section id="widget-grid" class="">
		<div class="row">
			<article class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
				<div class="jarviswidget jarviswidget-color-blueDark">
					<header>
						<span class="widget-icon"><i class="fa fa-table"></i></span>
						<h2>Liste des tickets</h2>
					</header>
					<div>
						<div class="widget-body">
							<a href="{{ path('tracker_ticket_ticket_add') }}" class="btn btn-labeled btn-primary">
								<span class="btn-label"><i class="glyphicon glyphicon-plus"></i></span>
								Ouvrir un nouveau ticket
							</a>
							<hr />
							
							{% if tickets %}
							<p>Retrouver ci dessous tous vos tickets.</p>
							<table class="table table-bordered">
								<thead>
									<tr>
										<th>Titre</th>
										<th>Réponses</th>
										<th>Type</th>
										<th>Date de création</th>
										<th>Date de fermeture</th>
										<th>Action</th>
									</tr>
								</thead>
								<tbody>
									{% for t in tickets %}
									    {% set class = '' %}
									    {% if not t.closed %} {% set class = 'warning' %} {% endif %}
									    {% if not t.messages.isEmpty %}
									        {% if t.messages.last.user.id != app.user.id %}
									            {% set class = 'success' %}
									        {% endif %}
									    {% endif %}
									    
										<tr class="{{ class }}">
											<td>{{ t.name }}</td>
											<td>{{ t.messages.count }}</td>
											<td>{{ t.typeDescription }}</td>
											<td>{{ t.created | date("d/m/Y H:i") }}</td>
											<td>{% if t.closed %}{{ t.closed | date("d/m/Y H:i") }}{% else %}Ouvert{% endif %}</td>
										    <td><a href="{{ path('tracker_ticket_ticket_view', {id: t.id}) }}" class="btn btn-primary btn-circle"><i class="glyphicon glyphicon-pencil"></i></a></td>
										</tr>
									{% endfor %}
								</tbody>
							</table>
							{% else %}
								<div class="alert alert-info alert-block">
									<i class="fa-fw fa fa-info"></i>
									Vous n'avez aucun ticket.
								</div>
							{% endif %}
						</div>
					</div>
				</div>
			</article>
		</div>
	</section>
</div>
{% endblock %}

src/Tracker/TicketBundle/Resources/views/Ticket/view.html.twig
{% extends "TrackerTicketBundle::layout.html.twig" %}

{% block breadcrumb %}
	<li><a href="{{ path('tracker_page_dashboard') }}">{{ 'Accueil'|trans }}</a></li>
	<li><a href="{{ path('tracker_ticket_ticket_index') }}">{{ 'Tickets'|trans }}</a></li>
	<li>{{ 'Ticket'|trans }} {{ ticket.id }}</li>
{% endblock %}

{% block ticket_body %}
<div id="content">
	<div class="row">
		<div class="col-xs-12 col-sm-7 col-md-7 col-lg-4">
			<h1 class="page-title txt-color-blueDark"><i class="fa fa-comments txt-color-white"></i> {{ 'Conversation'|trans }} </span></h1>
		</div>
	</div>
	
	<section id="widget-grid" class="">
		<div class="row">
			<article class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
				<div class="jarviswidget jarviswidget-color-blueDark">
					<header>
						<span class="widget-icon"><i class="fa fa-table"></i></span>
						<h2>Conversation</h2>
					</header>
					<div>
						<div class="widget-body widget-hide-overflow no-padding">
							
							<div class="chat-body custom-scroll">
								<ul>
									<li class="message">
										<img class="online" alt="" src="{{ asset('img/avatars/male.png') }}" />
										<div class="message-text">
											<time>{{ ticket.created | date("d/m/Y H:i") }}</time>
											<a class="username">{{ ticket.user.firstName }} {{ ticket.user.lastName }}</a>
											{{ ticket.description|nl2br }}
										</div>
									</li>
									
									{# On liste les messages #}
									{% for m in ticket.messages %}
										{% set avatar = 'male.png' %}
										{% if m.user.hasRole('ROLE_ADMIN') %}
											{% set avatar = '4.png' %}
										{% endif %}

    									<li class="message">
    										<img class="online" alt="" src="{{ asset('img/avatars/'~avatar) }}" />
    										<div class="message-text">
    											<time>{{ m.created | date("d/m/Y H:i") }}</time>
    											<a class="username">{{ m.user.firstName }} {{ m.user.lastName }}</a>
    											{{ m.content|nl2br }}
    										</div>
    									</li>
									{% endfor %}
								</ul>
							</div>
							
							{% if not ticket.closed %}
    							<div class="chat-footer">
    							<form method="POST">
    								<div class="textarea-div">
    									<div class="typearea">
    									    {{ form_widget(form.content) }}
    									</div>
    								</div>
    								<span class="textarea-controls">
    									<button class="btn btn-sm btn-primary pull-right">Répondre</button>
    									<span class="pull-right smart-form" style="margin-top: 3px; margin-right: 10px;">
    										<label class="checkbox pull-right">
    											{{ form_widget(form.close) }}
    											<i></i>
    											Fermer le ticket
    										</label>
    									</span>
    								</span>
    								{{ form_rest(form) }}
    							</form>
    							</div>
    						{% else %}
    						    <hr />
    						    <div class="alert alert-info alert-block">
									<i class="fa-fw fa fa-info"></i>
									Le ticket est fermé.
								</div>
							{% endif %}
						    
						    {% if not form.vars.valid %}
                                <div class="alert alert-danger">
                                    <button class="close"> x </button>
                                    <i class="fa-fw fa fa-times"></i>
                                    <strong>Une erreur est survenue!</strong>
                                    {{ form_errors(form) }}
                                </div>
                            {% endif %}
						
						</div>
					</div>
				</div>
			</article>
		</div>
	</section>
</div>
{% endblock %}